/* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

import { defineConfig } from "@forsakringskassan/vite-lib-config/vite";
import { defineTestConfig } from "@forsakringskassan/vitest-config-jsdom";

export default defineConfig({
    test: defineTestConfig(),
});
