<script lang="ts">
import { computed, defineComponent, shallowRef, useTemplateRef, watch, type PropType } from "vue";
import { FDate, FYear } from "@fkui/date";
import { ElementIdService, focus } from "@fkui/logic";
import { findHTMLElementFromVueRef } from "../../utils";
import { useYearSelector } from "../../components/FCalendar/useYearSelector";
import { useCalendarHeight } from "../../components/FCalendar/use-calendar-height";

export default defineComponent({
    name: "ICalendarYearSelector",
    props: {
        /**
         * Active month.
         * @model
         */
        modelValue: {
            type: Object as PropType<FDate>,
            required: true,
        },
        /**
         * Min date.
         */
        minDate: {
            type: Object as PropType<FDate>,
            required: true,
        },
        /**
         * Max date.
         */
        maxDate: {
            type: Object as PropType<FDate>,
            required: true,
        },
        /**
         * Optional id (generated by default).
         */
        id: {
            type: String,
            required: false,
            default: () => ElementIdService.generateElementId(),
        },
    },
    emits: [
        "click",

        /**
         * `v-model` event. Emitted when changing to a different month
         * or year in the calendar.
         *
         * @event update:modelValue
         * @type {FDate}
         */
        "update:modelValue",
    ],
    setup(props, context) {
        const modelValue = shallowRef(props.modelValue);
        const minDate = shallowRef(props.minDate);
        const maxDate = shallowRef(props.maxDate);

        const calendarRef = useTemplateRef("calendar");
        const yearElements = useTemplateRef("yearElements");
        const yearSelectorRef = useTemplateRef("yearSelector");
        const calendarNavbarRef = useTemplateRef("calendarNavbar");
        const calendar = computed(() => findHTMLElementFromVueRef(calendarRef.value) ?? null);
        const yearSelector = computed(() => findHTMLElementFromVueRef(yearSelectorRef.value) ?? null);
        const calendarNavbar = computed(() => findHTMLElementFromVueRef(calendarNavbarRef.value) ?? null);

        const { yearSelectorOpen, activeYear, selectableYears, onClickSelectYear } = useYearSelector({
            modelValue,
            yearElements,
            yearSelector,
            minDate,
            maxDate,
            onChangeDate,
            onClose,
        });

        /* store the height of src element as a css property on dst element */
        useCalendarHeight({
            src: calendar,
            dst: yearSelector,
            property: "--f-calendar-height",
        });

        watch(
            () => props.modelValue,
            (value) => (modelValue.value = value),
        );

        watch(
            () => props.minDate,
            (value) => (minDate.value = value),
        );

        watch(
            () => props.maxDate,
            (value) => (maxDate.value = value),
        );

        return {
            yearSelectorOpen,
            activeYear,
            selectableYears,
            onChangeDate,
            onClickSelectYear,
        };

        function onChangeDate(date: FDate): void {
            context.emit("update:modelValue", date);
        }

        function onClose(): void {
            const button = calendarNavbar.value?.querySelector("button");
            focus(button);
        }
    },
    computed: {
        yearNounText(): string {
            return this.$t("fkui.calendar.year-noun", "Årtal");
        },
    },
    methods: {
        getSelectableYearId(year: FYear) {
            return `${this.id}-year-${year.toString()}`;
        },
        onClickDay(date: FDate): void {
            /**
             * `click` event. Emitted when a calendar day is clicked.
             * @event click
             * @type {FDate}
             */
            this.$emit("click", date);
        },
    },
});
</script>

<template>
    <div ref="yearSelector" class="calendar__year-selector">
        <!-- [html-validate-disable-next prefer-native-element] -->
        <ul
            role="listbox"
            class="calendar__year-selector__listbox"
            :aria-activedescendant="getSelectableYearId(activeYear)"
            :aria-label="yearNounText"
        >
            <li
                v-for="year in selectableYears"
                :id="getSelectableYearId(year)"
                ref="yearElements"
                :key="year.value"
                role="option"
                :tabindex="activeYear.equals(year) ? 0 : -1"
                :aria-selected="activeYear.equals(year) ? 'true' : undefined"
                class="calendar__year-selector__year"
                :class="{ 'calendar__year-selector__year--highlight': activeYear.equals(year) }"
                @click.stop.prevent="onClickSelectYear(year)"
            >
                {{ year }}
            </li>
        </ul>
    </div>
</template>
