<script lang="ts">
import { capitalize, defineComponent, type PropType } from "vue";
import { type FDate } from "@fkui/date";
import { alertScreenReader, ElementIdService } from "@fkui/logic";
import { FIcon } from "../../components/FIcon";
import { TranslationMixin } from "../../plugins";
import { isInvalidMonth } from "./is-invalid-month";
import { getMessage } from "./get-message";

export default defineComponent({
    name: "ICalendarNavbar",
    components: {
        FIcon,
    },
    mixins: [TranslationMixin],
    props: {
        /**
         * Focused month.
         */
        modelValue: {
            type: Object as PropType<FDate>,
            required: true,
        },
        /**
         * Min date.
         */
        minDate: {
            type: Object as PropType<FDate>,
            required: true,
        },
        /**
         * Max date.
         */
        maxDate: {
            type: Object as PropType<FDate>,
            required: true,
        },
        /**
         * Includes a year selector when enabled.
         */
        yearSelector: {
            type: Boolean,
            required: false,
        },
        /**
         * Displays the year selector as open when enabled.
         */
        yearSelectorOpen: {
            type: Boolean,
            required: false,
        },
        /**
         * Optional id (generated by default).
         */
        id: {
            type: String,
            required: false,
            default: () => ElementIdService.generateElementId(),
        },
    },
    emits: [
        "change",
        /**
         * V-model event.
         * @param value
         * @type {FDate}
         */
        "update:modelValue",
        /**
         * Emitted when year selector is opened or closed.
         * @type {boolean}
         */
        "update:yearSelectorOpen",
    ],
    computed: {
        previousDisabled(): boolean {
            return isInvalidMonth(this.modelValue.addMonths(-1), this.minDate, this.maxDate);
        },
        nextDisabled(): boolean {
            return isInvalidMonth(this.modelValue.addMonths(1), this.minDate, this.maxDate);
        },
        previousValue(): FDate {
            return this.modelValue.addMonths(-1);
        },
        nextValue(): FDate {
            return this.modelValue.addMonths(1);
        },
        currentText(): string {
            return this.getDateText(this.modelValue);
        },
        previousSrText(): string {
            return this.$t("fkui.calendar-navbar.previous", "Föregående månad");
        },
        nextSrText(): string {
            return this.$t("fkui.calendar-navbar.next", "Nästa månad");
        },
        openYearSelectorText(): string {
            return this.$t("fkui.calendar-navbar.open-year-selector", "Öppna årsväljare");
        },
        closeYearSelectorText(): string {
            return this.$t("fkui.calendar-navbar.close-year-selector", "Stäng årsväljare");
        },
        previousIconClasses(): Record<string, boolean> {
            return {
                "calendar-navbar__icon": true,
                "calendar-navbar__icon--disabled": this.previousDisabled,
            };
        },
        nextIconClasses(): Record<string, boolean> {
            return {
                "calendar-navbar__icon": true,
                "calendar-navbar__icon--disabled": this.nextDisabled,
            };
        },
        monthTitleClass(): string {
            return this.yearSelector ? "sr-only" : "";
        },
    },
    methods: {
        onClickYearSelector() {
            this.changeDisplayYearSelectorAsOpen(!this.yearSelectorOpen);
        },
        onClickPreviousButton(): void {
            if (!this.previousDisabled) {
                this.$emit("update:modelValue", this.previousValue);

                const previousMonth = this.getDateText(this.previousValue);
                const previousMonthText = this.$t("fkui.calendar-navbar.previous-month", "{{ previousMonth }} visas", {
                    previousMonth,
                });
                alertScreenReader(previousMonthText, { assertive: true });
                return;
            }

            const message = getMessage(this.$t, this.previousValue, this.minDate, this.maxDate);
            if (message) {
                alertScreenReader(message, { assertive: true });
            }
        },
        onClickNextButton(): void {
            if (!this.nextDisabled) {
                this.$emit("update:modelValue", this.nextValue);
                this.$emit("change", this.nextValue);

                const nextMonth = this.getDateText(this.nextValue);
                const nextMonthText = this.$t("fkui.calendar-navbar.next-month", "{{ nextMonth }} visas", {
                    nextMonth,
                });
                alertScreenReader(nextMonthText, { assertive: true });
                return;
            }

            const message = getMessage(this.$t, this.nextValue, this.minDate, this.maxDate);
            if (message) {
                alertScreenReader(message, { assertive: true });
            }
        },
        onCloseYearSelector() {
            this.changeDisplayYearSelectorAsOpen(false);
        },
        changeDisplayYearSelectorAsOpen(value: boolean) {
            this.$emit("update:yearSelectorOpen", value);
        },
        getDateText(value: FDate): string {
            return `${capitalize(value.monthName)} ${String(value.year)}`;
        },
        isFocused(ref: string): boolean {
            return document.activeElement === this.$refs[ref];
        },
    },
});
</script>

<template>
    <div class="calendar-navbar">
        <div class="calendar-navbar__month">
            <span
                :class="monthTitleClass"
                class="calendar-navbar__month--title"
                tabindex="-1"
                :aria-live="isFocused('yearSelectorButton') ? 'polite' : 'off'"
            >
                {{ currentText }}
            </span>

            <!-- Button - Open/close year selector -->
            <button
                v-if="yearSelector"
                :id="`${id}`"
                ref="yearSelectorButton"
                class="calendar-navbar__year-selector-button"
                type="button"
                aria-haspopup="listbox"
                :aria-expanded="yearSelectorOpen"
                @click.stop.prevent="onClickYearSelector"
            >
                <span class="calendar-navbar__year-selector-button--title" aria-hidden="true">{{ currentText }}</span>
                <span class="sr-only"> {{ yearSelectorOpen ? closeYearSelectorText : openYearSelectorText }} </span>
                <f-icon :class="yearSelectorOpen ? 'calendar-navbar__arrow--up' : undefined" name="arrow-down" />
            </button>
        </div>

        <button
            v-if="!yearSelectorOpen"
            ref="previousButton"
            class="calendar-navbar__arrow calendar-navbar__arrow--previous"
            type="button"
            :aria-disabled="previousDisabled"
            :aria-live="isFocused('previousButton') ? 'polite' : 'off'"
            @click.stop="onClickPreviousButton"
        >
            <span class="sr-only">
                {{ previousSrText }}
            </span>
            <f-icon :class="previousIconClasses" name="arrow-right"></f-icon>
        </button>

        <button
            v-if="!yearSelectorOpen"
            ref="nextButton"
            class="calendar-navbar__arrow calendar-navbar__arrow--next"
            type="button"
            :aria-disabled="nextDisabled"
            :aria-live="isFocused('nextButton') ? 'polite' : 'off'"
            @click.stop="onClickNextButton"
        >
            <span class="sr-only">{{ nextSrText }}</span>
            <f-icon :class="nextIconClasses" name="arrow-right"></f-icon>
        </button>
    </div>
</template>
