<script lang="ts">
import { computed, defineComponent, shallowRef, useTemplateRef, watch, type PropType } from "vue";
import { FDate, FYear } from "@fkui/date";
import { ElementIdService, focus } from "@fkui/logic";
import ICalendarNavbar from "../../internal-components/calendar/ICalendarNavbar.vue";
import ICalendarMonth from "../../internal-components/calendar/ICalendarMonth.vue";
import { findHTMLElementFromVueRef } from "../../utils";
import { useYearSelector } from "./useYearSelector";
import { useCalendarHeight } from "./use-calendar-height";

export default defineComponent({
    name: "FCalendar",
    components: {
        ICalendarNavbar,
        ICalendarMonth,
    },
    props: {
        /**
         * Active month.
         */
        modelValue: {
            type: Object as PropType<FDate>,
            required: true,
        },
        /**
         * Date to set tabindex on when component gains focus.
         *
         * Consumers can update this related to active month.
         * If undefined, the first day of the month will gain focus.
         */
        tabDate: {
            type: Object as PropType<FDate | undefined>,
            required: false,
            default: undefined,
        },
        /**
         * Min date.
         */
        minDate: {
            type: Object as PropType<FDate>,
            required: true,
        },
        /**
         * Max date.
         */
        maxDate: {
            type: Object as PropType<FDate>,
            required: true,
        },
        /**
         * Includes a year selector when enabled.
         */
        yearSelector: {
            type: Boolean,
            required: false,
            default: false,
        },
        /**
         * Optional id (generated by default).
         */
        id: {
            type: String,
            required: false,
            default: () => ElementIdService.generateElementId(),
        },
    },
    emits: {
        /**
         * `click` event. Emitted when a calendar day is clicked.
         */
        click(_date: FDate) {
            return true;
        },

        /**
         * `v-model` event. Emitted when changing to a different month
         * or year in the calendar.
         */
        "update:modelValue"(_date: FDate) {
            return true;
        },
    },
    setup(props, context) {
        const modelValue = shallowRef(props.modelValue);
        const minDate = shallowRef(props.minDate);
        const maxDate = shallowRef(props.maxDate);

        const calendarRef = useTemplateRef("calendar");
        const yearElements = useTemplateRef("yearElements");
        const yearSelectorRef = useTemplateRef("yearSelector");
        const calendarNavbarRef = useTemplateRef("calendarNavbar");
        const calendar = computed(() => findHTMLElementFromVueRef(calendarRef.value) ?? null);
        const yearSelector = computed(() => findHTMLElementFromVueRef(yearSelectorRef.value) ?? null);
        const calendarNavbar = computed(() => findHTMLElementFromVueRef(calendarNavbarRef.value) ?? null);

        const { yearSelectorOpen, activeYear, selectableYears, onClickSelectYear } = useYearSelector({
            modelValue,
            yearElements,
            yearSelector,
            minDate,
            maxDate,
            onChangeDate,
            onClose,
        });

        /* store the height of src element as a css property on dst element */
        useCalendarHeight({
            src: calendar,
            dst: yearSelector,
            property: "--f-calendar-height",
        });

        watch(
            () => props.modelValue,
            (value) => (modelValue.value = value),
        );

        watch(
            () => props.minDate,
            (value) => (minDate.value = value),
        );

        watch(
            () => props.maxDate,
            (value) => (maxDate.value = value),
        );

        return {
            yearSelectorOpen,
            activeYear,
            selectableYears,
            onChangeDate,
            onClickSelectYear,
        };

        function onChangeDate(date: FDate): void {
            context.emit("update:modelValue", date);
        }

        function onClose(): void {
            const button = calendarNavbar.value?.querySelector("button");
            focus(button);
        }
    },
    computed: {
        yearNounText(): string {
            return this.$t("fkui.calendar.year-noun", "Årtal");
        },
    },
    methods: {
        getSelectableYearId(year: FYear) {
            return `${this.id}-year-${year.toString()}`;
        },
        onClickDay(date: FDate): void {
            this.$emit("click", date);
        },
    },
});
</script>

<template>
    <div class="calendar__wrapper">
        <i-calendar-navbar
            :id
            ref="calendarNavbar"
            v-model:year-selector-open="yearSelectorOpen"
            :model-value="modelValue"
            :min-date="minDate"
            :max-date="maxDate"
            :year-selector
            @update:model-value="onChangeDate"
        ></i-calendar-navbar>

        <div v-if="yearSelectorOpen" ref="yearSelector" class="calendar__year-selector">
            <!-- [html-validate-disable-next prefer-native-element] -->
            <ul
                role="listbox"
                class="calendar__year-selector__listbox"
                :aria-activedescendant="getSelectableYearId(activeYear)"
                :aria-label="yearNounText"
            >
                <li
                    v-for="year in selectableYears"
                    :id="getSelectableYearId(year)"
                    ref="yearElements"
                    :key="year.value"
                    role="option"
                    :tabindex="activeYear.equals(year) ? 0 : -1"
                    :aria-selected="activeYear.equals(year) ? 'true' : undefined"
                    class="calendar__year-selector__year"
                    :class="{ 'calendar__year-selector__year--highlight': activeYear.equals(year) }"
                    @click.stop.prevent="onClickSelectYear(year)"
                >
                    {{ year }}
                </li>
            </ul>
        </div>

        <i-calendar-month
            v-else
            ref="calendar"
            :model-value="modelValue"
            :min-date="minDate"
            :max-date="maxDate"
            :tab-date="tabDate"
            @click="onClickDay"
            @update:model-value="onChangeDate"
        >
            <template #default="{ date, focused }">
                <!--
                @slot Slot for calendar day.
                @binding {FDate} date The date object for the current day.
                @binding {boolean} is-focused Indicates whether the current day is focused.
                -->
                <slot :date="date" :is-focused="focused"></slot>
            </template>
        </i-calendar-month>
    </div>
</template>
