<script lang="ts">
import { defineComponent, shallowRef, useTemplateRef, watch, type PropType } from "vue";
import { FDate } from "@fkui/date";
import { ElementIdService } from "@fkui/logic";
import ICalendarNavbar from "../../internal-components/calendar/ICalendarNavbar.vue";
import ICalendarMonth from "../../internal-components/calendar/ICalendarMonth.vue";
import { useYearSelector } from "./useYearSelector";

export default defineComponent({
    name: "FCalendar",
    components: {
        ICalendarNavbar,
        ICalendarMonth,
    },
    props: {
        /**
         * Active month.
         * @model
         */
        modelValue: {
            type: Object as PropType<FDate>,
            required: true,
        },
        /**
         * Date to set tabindex on when component gains focus.
         *
         * Consumers can update this related to active month.
         * If undefined, the first day of the month will gain focus.
         */
        tabDate: {
            type: Object as PropType<FDate | undefined>,
            required: false,
            default: undefined,
        },
        /**
         * Min date.
         */
        minDate: {
            type: Object as PropType<FDate>,
            required: true,
        },
        /**
         * Max date.
         */
        maxDate: {
            type: Object as PropType<FDate>,
            required: true,
        },
        /**
         * Includes a year selector when enabled.
         */
        yearSelector: {
            type: Boolean,
            required: false,
            default: false,
        },
        /**
         * Optional id (generated by default).
         */
        id: {
            type: String,
            required: false,
            default: () => ElementIdService.generateElementId(),
        },
    },
    emits: ["click", "update:modelValue"],
    setup(props, context) {
        const modelValue = shallowRef(props.modelValue);
        const minDate = shallowRef(props.minDate);
        const maxDate = shallowRef(props.maxDate);
        const calendar = useTemplateRef("calendar");
        const yearElements = useTemplateRef("yearElements");
        const yearSelector = useTemplateRef("yearSelector");
        const calendarNavbar = useTemplateRef("calendarNavBar");
        const {
            onUpdateDisplayYearSelectorAsOpen,
            yearSelectorStyle,
            displayYearSelectorAsOpen,
            activeYear,
            onYearSelectorKeyDown,
            onClickSelectYear,
            selectableYears,
        } = useYearSelector({
            calendar,
            modelValue,
            yearElements,
            yearSelector,
            calendarNavbar,
            minDate,
            maxDate,
            onChangeDate,
        });

        watch(
            () => props.modelValue,
            (value) => (modelValue.value = value),
        );

        watch(
            () => props.minDate,
            (value) => (minDate.value = value),
        );

        watch(
            () => props.maxDate,
            (value) => (maxDate.value = value),
        );

        function onChangeDate(date: FDate): void {
            /**
             * `v-model` event. Emitted when changing to a different month or year in the calendar.
             * @event update:modelValue
             * @type {FDate}
             */
            context.emit("update:modelValue", date);
        }

        return {
            displayYearSelectorAsOpen,
            onChangeDate,
            onUpdateDisplayYearSelectorAsOpen,
            yearSelectorStyle,
            activeYear,
            selectableYears,
            onYearSelectorKeyDown,
            onClickSelectYear,
        };
    },
    methods: {
        getSelectableYearId(year: number) {
            return `${this.id}-year-${year}`;
        },
        onClickDay(date: FDate): void {
            /**
             * `click` event. Emitted when a calendar day is clicked.
             * @event click
             * @type {FDate}
             */
            this.$emit("click", date);
        },
    },
});
</script>

<template>
    <div class="calendar__wrapper">
        <i-calendar-navbar
            :id
            ref="calendarNavbar"
            :model-value="modelValue"
            :min-date="minDate"
            :max-date="maxDate"
            :year-selector
            :display-year-selector-as-open
            @update:model-value="onChangeDate"
            @update:display-year-selector-as-open="onUpdateDisplayYearSelectorAsOpen"
        ></i-calendar-navbar>

        <!-- [html-validate-disable-next no-inline-style] -->
        <div
            v-if="displayYearSelectorAsOpen"
            ref="yearSelector"
            class="calendar__year-selector"
            :style="yearSelectorStyle"
        >
            <!-- [html-validate-disable-next prefer-native-element] -->
            <ul
                role="listbox"
                class="calendar__year-selector__listbox"
                :aria-activedescendant="getSelectableYearId(activeYear)"
                aria-label="Årtal"
            >
                <li
                    v-for="year in selectableYears"
                    :id="getSelectableYearId(year)"
                    ref="yearElements"
                    :key="year"
                    role="option"
                    :tabindex="activeYear === year ? 0 : -1"
                    :aria-selected="activeYear === year ? 'true' : undefined"
                    :aria-labelledby="getSelectableYearId(year)"
                    class="calendar__year-selector__year"
                    :class="{ 'calendar__year-selector__year--highlight': activeYear === year }"
                    @keydown="onYearSelectorKeyDown"
                    @click.stop.prevent="onClickSelectYear(year)"
                >
                    {{ year }}
                </li>
            </ul>
        </div>

        <i-calendar-month
            v-else
            ref="calendar"
            :model-value="modelValue"
            :min-date="minDate"
            :max-date="maxDate"
            :tab-date="tabDate"
            @click="onClickDay"
            @update:model-value="onChangeDate"
        >
            <template #default="{ date, focused }">
                <!--
                @slot Slot for calendar day.
                @binding {FDate} date The date object for the current day.
                @binding {boolean} is-focused Indicates whether the current day is focused.
                -->
                <slot :date="date" :is-focused="focused"></slot>
            </template>
        </i-calendar-month>
    </div>
</template>
