#!/bin/bash

# Finds all files matching any of the patterns and replaces the %version%
# placeholder with the actual version from the new release.

patterns=(
	'**/*.css'
	'**/*.md'
	'**/*.scss'
	'**/*.ts'
	'**/*.vue'
)

exempt=(
	# this is an example/skeleton where we want the placeholder intact
	"packages/vue/src/selectors/XExample.selectors.ts"
)

for file in $(git ls-files "${patterns[@]}"); do
	# ignore anything in these folders
	if [[ "${file}" == scripts/* || "${file}" == etc/* ]]; then
		continue
	fi

	# ignore files in the exempt list
	if [[ " ${exempt[*]} " =~ [[:space:]]${file}[[:space:]] ]]; then
		continue
	fi

	# inline global substitution with the 'w' flag to pipe the changes to grep
	# which matches if any changes was made.
	if sed "s/%version%/v${npm_new_version}/gw /dev/stdout" -i "${file}" | grep -q .; then
		echo "${file}"
		git add "${file}"
	fi
done
