<script setup lang="ts">
import { computed, ref, type PropType, onMounted } from "vue";
import { ElementIdService, type ValidityEvent } from "@fkui/logic";
import { useSlotUtils } from "../../composables";
import { dispatchComponentValidityEvent } from "../../utils";
import { FIcon } from "../FIcon";
import { IFlex, IFlexItem } from "../../internal-components/IFlex";

const { hasSlot } = useSlotUtils();
const validationMessage = ref("");
const hasError = ref(false);
const isMounted = ref(false);

const hasHeaderSlot = computed(() => hasSlot("header"));
const hasFooterSlot = computed(() => hasSlot("footer"));
const cardClass = computed(() => `card card--${hasError.value ? "error" : "default"}`);

const props = defineProps({
    /**
     * Element to focus on when card is invalid. Set when using validation.
     */
    focusRef: {
        type: Object as PropType<HTMLElement | null>,
        required: false,
        default: null,
    },
    /**
     * Optional id (generated by default).
     */
    id: {
        type: String,
        required: false,
        default: () => ElementIdService.generateElementId(),
    },
});

onMounted(() => (isMounted.value = true));

async function onValidity({ detail }: CustomEvent<ValidityEvent>): Promise<void> {
    if (!isMounted.value) {
        return;
    }

    // ignore validity events triggered by child components
    if (detail.elementId !== props.id) {
        return;
    }

    if (!props.focusRef) {
        throw new Error(
            "Element to focus on when card is invalid (`focusRef`) is required when using card validation.",
        );
    }

    const focusElementId = props.focusRef.id;
    if (!focusElementId) {
        throw new Error("An id must be set on the card's focus element.");
    }

    hasError.value = !detail.isValid;
    validationMessage.value = detail.validationMessage;

    dispatchComponentValidityEvent(props.focusRef, {
        ...detail,
        errorMessage: validationMessage.value,
        focusElementId,
    });
}
</script>

<template>
    <div :id :class="cardClass" @validity="onValidity">
        <div v-if="hasHeaderSlot" class="card__header">
            <!--
            @slot Slot for the title.
            @binding {string} headingSlotClass CSS class for styling the header label.
            -->
            <slot name="header" v-bind="{ headingSlotClass: 'card__header-label' }"></slot>
        </div>

        <!--
        @slot Slot for displaying error message.
        @binding {boolean} hasError Indicates whether a validation error is present.
        @binding {string} validationMessage Descriptive validation error message for current error.
        -->
        <slot name="error-message" v-bind="{ hasError, validationMessage }">
            <template v-if="hasError">
                <i-flex gap="1x" class="card__error-message">
                    <i-flex-item shrink align="center"> <f-icon name="error"></f-icon> </i-flex-item>
                    <i-flex-item grow> {{ validationMessage }} </i-flex-item>
                </i-flex>
            </template>
        </slot>

        <div class="card__content">
            <!--@slot Slot for the main content, e.g. paragraphs, input fields, etc. -->
            <slot name="default"></slot>
        </div>

        <div v-if="hasFooterSlot" class="card__footer">
            <!--
            @slot Slot the footer content, i.e. buttons.
            @binding {boolean} hasError Indicates whether a validation error is present.
            @binding {string} validationMessage Descriptive validation error message for current error.
            -->
            <slot name="footer" v-bind="{ hasError, validationMessage }"></slot>
        </div>
    </div>
</template>
