name: Clean gh-pages history

on:
    workflow_dispatch:
        description: "Manually clean the gh-pages branch history"

permissions:
    contents: write

jobs:
    clean-history:
        name: Clean gh-pages history
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
              with:
                  ref: "gh-pages"
            - name: Configure git
              run: |
                  git config --global user.email "${{ vars.DOCS_DEPLOY_EMAIL }}"
                  git config --global user.name "${{ vars.DOCS_DEPLOY_NAME }}"
            - name: Create orphan branch
              run: |
                  git checkout --orphan new-gh-pages
            - name: Commit changes
              run: |
                  git commit -m "Clean gh-pages history"
            - name: Push changes
              run: |
                  git push origin new-gh-pages:gh-pages --force-with-lease
