name: Docs (main)
concurrency: docs-${{ github.ref }}

on:
    push:
        branches: ["main"]

permissions:
    contents: write

jobs:
    docs:
        name: Deploy docs from main branch
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  ref: "${{ github.ref_name }}"
            - name: Use Node.js 22.x
              uses: actions/setup-node@v6
              with:
                  node-version: 22.x
            - name: Install dependencies
              run: npm ci
            - name: Build documentation
              uses: ./.github/actions/build-docs
              with:
                  example-apps: true
                  sandbox: false
            - name: Deploy documentation
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: public
                  target-folder: main
                  clean: true
                  branch: gh-pages
                  git-config-name: ${{ vars.DOCS_DEPLOY_NAME }}
                  git-config-email: ${{ vars.DOCS_DEPLOY_EMAIL }}
                  commit-message: "chore(release): [skip ci] deploy documentation from main branch"
