name: Integration

on: [push, pull_request]

permissions:
    contents: read

jobs:
    integration:
        name: Integration test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - name: Use Node.js 22.x
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: 22.x
            - name: Install dependencies
              run: npm ci
            - name: Build packages
              run: npm run build
            - name: Remove conflicting dependencies
              run: |
                  npm rm --include-workspace-root --workspaces \
                      @forsakringskassan/docs-live-example
            - name: Install minimum declared versions
              run: |
                  VERSION=$(npx -y -w @fkui/vue npm-min-peer vue)
                  npm install --force --include-workspace-root --workspaces \
                      vue@${VERSION} \
                      @vue/server-renderer@${VERSION}
                  npm ls vue @vue/server-renderer
            - name: Build sandbox
              run: npm run -w @fkui/vue-sandbox build
