name: Lint

on: [push, pull_request]

permissions:
    contents: read

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            - name: Use Node.js 22.x
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: 22.x
            - name: Install dependencies
              run: npm ci
            - name: Minimal build
              run: npm exec lerna -- run --include-dependencies --scope=@fkui/theme-default --scope=@fkui/vue --scope=@fkui/vue-labs --scope=@fkui/cypress-split build
            - name: Prettier
              uses: Forsakringskassan/prettier-config@61d943c9670135cb565338d55f1e571ad698b9c2 # v3.7.4
            - name: ESLint
              if: success() || failure()
              uses: Forsakringskassan/eslint-config@2853a55079e2ca1e5ddef7e3fb7fbd2f2b25876f # v15.1.9
            - name: HTML Validate
              if: success() || failure()
              run: npm run html-validate -- --max-warnings 0 || false
            - name: Stylelint
              if: success() || failure()
              run: npm run stylelint -- --max-warnings 0
            - name: pnr-scanner
              if: success() || failure()
              run: |
                  errors=$(npx pnr-scanner . 2> /dev/null | egrep "    " | wc -l)
                  if [[ "${errors}" != "0" ]]; then
                      echo "Found ${errors} potential personnummer. Rerun `npx pnr-scanner .` locally for more information."
                      exit 1
                  fi
    npm-pkg-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            - name: Use Node.js 22.x
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: 22.x
            - name: Install Dependencies
              run: npm ci
            - name: npm-pkg-lint
              uses: ext/npm-pkg-lint@e9d1941bd43a0e086df25f4be2d512ba0e2bb8eb # v5.1.9
              with:
                  folders: packages/*
                  allow-dependencies: fk-icons
