name: Lint

on: [push, pull_request]

permissions:
    contents: read

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - name: Use Node.js 22.x
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: 22.x
            - name: Install dependencies
              run: npm ci
            - name: Minimal build
              run: npm exec lerna -- run --include-dependencies --scope=@fkui/theme-default --scope=@fkui/vue --scope=@fkui/vue-labs --scope=@fkui/cypress-split build
            - name: Prettier
              uses: Forsakringskassan/prettier-config@0a8ef8dbb948f3dc4e03aa6ba6d259b383d8aed1 # v3.6.0
            - name: ESLint
              if: success() || failure()
              uses: Forsakringskassan/eslint-config@da71744b003f95ee2ac3ce36b2ecdcaf63410a02 # v15.0.6
            - name: HTML Validate
              if: success() || failure()
              run: npm run html-validate -- --max-warnings 0 || false
            - name: Stylelint
              if: success() || failure()
              run: npm run stylelint -- --max-warnings 0
            - name: pnr-scanner
              if: success() || failure()
              run: |
                  errors=$(npx pnr-scanner . 2> /dev/null | egrep "    " | wc -l)
                  if [[ "${errors}" != "0" ]]; then
                      echo "Found ${errors} potential personnummer. Rerun `npx pnr-scanner .` locally for more information."
                      exit 1
                  fi
    npm-pkg-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - name: Use Node.js 22.x
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: 22.x
            - name: Install Dependencies
              run: npm ci
            - name: npm-pkg-lint
              uses: ext/npm-pkg-lint@b7f53dadcdde76d39ccf425daf9fb6a7db374b70 # master
              with:
                  folders: packages/*
                  allow-dependencies: fk-icons
