name: Lint

on: [push, pull_request]

permissions:
    contents: read

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            - name: Use Node.js 22.x
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
              with:
                  node-version: 22.x
            - name: Install dependencies
              run: npm ci
            - name: Minimal build
              run: npm exec lerna -- run --include-dependencies --scope=@fkui/theme-default --scope=@fkui/vue --scope=@fkui/vue-labs --scope=@fkui/cypress-split build
            - name: Prettier
              uses: Forsakringskassan/prettier-config@af7b8bc222a38143e50e156cd4c23dd2010b95ee # v3.7.8
            - name: ESLint
              if: success() || failure()
              uses: Forsakringskassan/eslint-config@f5358269d9903c094181ab1628362e9a4d8bdb57 # v15.4.5
            - name: HTML Validate
              if: success() || failure()
              run: npm run html-validate -- --max-warnings 0 || false
            - name: Stylelint
              if: success() || failure()
              run: npm run stylelint -- --max-warnings 0
            - name: pnr-scanner
              if: success() || failure()
              run: |
                  errors=$(npx pnr-scanner . 2> /dev/null | egrep "    " | wc -l)
                  if [[ "${errors}" != "0" ]]; then
                      echo "Found ${errors} potential personnummer. Rerun `npx pnr-scanner .` locally for more information."
                      exit 1
                  fi
    npm-pkg-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
            - name: Use Node.js 22.x
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
              with:
                  node-version: 22.x
            - name: Install Dependencies
              run: npm ci
            - name: npm-pkg-lint
              uses: ext/npm-pkg-lint@8fb16e59f1062fd9f03c8092c522ce5ed6c6e89e # v5.2.1
              with:
                  folders: packages/*
                  allow-dependencies: fk-icons
