name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - closed
jobs:
    deploy-preview:
        if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: Install and build
              if: github.event.action != 'closed'
              run: |
                  npm ci
                  npm exec lerna -- run build \
                      --include-dependencies \
                      --scope=@fkui/i18next-translate \
                      --scope=@fkui/testbed-page-layout \
                      --scope=@fkui/vue \
                      --scope=@fkui/vue-labs \
                      --scope=@fkui/vue-sandbox
                  npm run build:docs
            - uses: rossjrw/pr-preview-action@v1
              id: preview
              with:
                  source-dir: ./public/
                  preview-branch: gh-pages
                  umbrella-dir: pr-preview
                  action: auto
                  comment: false
            - name: Leave a comment after deployment
              if: steps.preview.outputs.deployment-action == 'deploy' && env.deployment_status == 'success'
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  header: pr-preview
                  message: |
                      ##  Förhandsgranskning :bug: :mag:

                      Dokumentation och exampel applikationer finns att förhandsgranska på:

                      | Sida | URL |
                      |-|-
                      | Dokumentation | ${{ steps.preview.outputs.preview-url }} |
                      | Vue Sandbox | ${{ steps.preview.outputs.preview-url }}/vue-sandbox |
                      | Applikationsmall | ${{ steps.preview.outputs.preview-url }}/testbed-page-layout |

                      ---

                      ###### Senast uppdaterad ${{ steps.preview.outputs.action-start-time }} i [gh-pages](${{ github.server_url }}/${{ github.repository }}/tree/gh-pages).

            - uses: marocchino/sticky-pull-request-comment@v2
              if: steps.preview-step.outputs.deployment-action == 'remove' && env.deployment_status == 'success'
              with:
                  header: pr-preview
                  message: |
                      ##  Förhandsgranskning :bug: :mag:

                      Förhandsgranskning borttagen då pull request är stängd.
