name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - closed
jobs:
    deploy-preview:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: Install and build
              if: github.event.action != 'closed'
              run: |
                  npm ci
                  npm exec lerna -- run --include-dependencies --scope=@fkui/vue --scope=@fkui/vue-labs build
                  npm run build:docs
            - uses: rossjrw/pr-preview-action@v1
              with:
                  source-dir: ./public/
                  preview-branch: gh-pages
                  umbrella-dir: pr-preview
                  action: auto
